language: go
sudo: false

env:
  GO111MODULE=on

go:
    - 1.11.x
    - 1.12.x

go_import_path: gopkg.in/src-d/go-billy-siva.v4

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

script:
  - make dependencies
  - make test-coverage
  - make codecov


jobs:
  include:
    - go: 1.12
      os: osx
      osx_image: xcode9.3

    - go: 1.12
      os: windows
      before_install:
        - powershell -command 'Set-MpPreference -DisableRealtimeMonitoring $true'
        - choco install make
